[package]
name = "snpm-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
snpm-core = { path = "../snpm-core" }
clap = { version = "4", features = ["derive"] }
anyhow.workspace = true
tokio = { version = "1.39.0", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["fmt", "env-filter"] }
